apiVersion: addon.cluster.x-k8s.io/v1alpha1
kind: KubewardenAddon
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-addon-provider-kubewarden
    app.kubernetes.io/managed-by: kustomize
  name: kubewardenaddon-sample
spec:
  version: v0.1.0
  imageRepository: ghcr.io/kubewarden/kubewarden-controller:v1.18.0
  policyServerConfig: 
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
