apiVersion: addon.cluster.x-k8s.io/v1alpha1
kind: KubewardenAddon
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-addon-provider-kubewarden
    app.kubernetes.io/managed-by: kustomize
  name: kubewardenaddon-sample
spec:
  version: ""
  imageRepository: ghcr.io/kubewarden/kubewarden-controller
  clusterSelector:
    matchLabels:
      environment: production
    matchExpressions:
      - { key: tier, operator: In, values: [frontend, backend] }
  policyServerConfig: 
    replicas: 1
    resources:
      cpu: 100m
      memory: 128Mi
