name: Build and Publish Nightly Docker images

on:
  schedule:
    - cron: "0 0 * * *" # Run daily
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  ORG: caapkw

jobs:
  build-and-publish-ghcr:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5.1.0
      with:
        go-version: '=1.22.0'

    - name: Verify Docker login
      run: docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker --version
        docker buildx create --use
        docker buildx inspect --bootstrap
        make docker-build-and-push TAG=${{ github.sha }} REGISTRY=${{ env.REGISTRY }} ORG=${{ env.ORG }}
