name: Build and Publish Nightly Docker images

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight (UTC)
  workflow_dispatch: # Allow running manually on demand

env:
  REGISTRY: ghcr.io
  ORG: caapkw

jobs:
  build-and-publish-ghcr:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v5.1.0
      with:
        go-version: '=1.22.0'

    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        make docker-build-and-push TAG=${{ github.sha }} REGISTRY=${{ env.REGISTRY }} ORG=${{ env.ORG }}
